### ISSUE TITLE
220531 'decoded_manifest' referenced before assignment

### ISSUE THREAD

**Issue by j5Jb3X4eYs** [obsidianforensics/hindsight#125]
[220531_hindsight.log](https://github.com/obsidianforensics/hindsight/files/8806819/220531_hindsight.log)

hindsight from the cli:
Traceback (most recent call last):
                  File "hindsight.py", line 335, in <module>
                  File "hindsight.py", line 212, in main
                  File "pyhindsight\analysis.py", line 529, in run
                  File "pyhindsight\browsers\chrome.py", line 2393, in process
                  File "pyhindsight\browsers\chrome.py", line 1045, in get_extensions
                UnboundLocalError: local variable 'decoded_manifest' referenced before assignment
                [12620] Failed to execute script 'hindsight' due to unhandled exception!

hindsight_gui:
Error: 500 Internal Server Error
Sorry, the requested URL 'http://localhost:8080/run' caused an error:

Internal Server Error
Exception:
UnboundLocalError("local variable 'decoded_manifest' referenced before assignment")
Traceback:
Traceback (most recent call last):
  File "bottle.py", line 868, in _handle
  File "bottle.py", line 1748, in wrapper
  File "hindsight_gui.py", line 170, in do_run
  File "pyhindsight\analysis.py", line 529, in run
  File "pyhindsight\browsers\chrome.py", line 2393, in process
  File "pyhindsight\browsers\chrome.py", line 1045, in get_extensions
UnboundLocalError: local variable 'decoded_manifest' referenced before assignment

**Comment by obsidianforensics** [comment]
Thanks for reporting, and sorry for the delay in addressing.
