### ISSUE TITLE
App fails with 'blockNumber' Attribute Error

### ISSUE THREAD

**Issue by cshanahan** [obsidianforensics/hindsight#15]
Using version 2.0.0, both hindsight.exe and the Web front-end, hingsight_gui.exe, produces the same error message and the app fails.

**Error produced by hindsight.exe**
> Input directory: c:\Users\cms\Documents\Cases\HindsightTest\Export\User Data\Default
Output name: HindsightTest.xlsx
Processing:
Detected Chrome version: [ 54-56 ]
URL records:             [   272 ]
Download records:        [    27 ]
Traceback (most recent call last):
  File "hindsight.py", line 286, in <module>
  File "hindsight.py", line 172, in main
  File "pyhindsight\analysis.py", line 135, in run
  File "pyhindsight\browsers\chrome.py", line 1169, in process
  File "pyhindsight\browsers\chrome.py", line 1019, in get_cache
  File "pyhindsight\browsers\chrome.py", line 1801, in __init__
  File "pyhindsight\browsers\chrome.py", line 1842, in keyToStr
  File "pyhindsight\browsers\chrome.py", line 1642, in data
AttributeError: CacheAddress instance has no attribute 'blockNumber'
Failed to execute script hindsight

**Error produced by hindsight_gui.exe**
> Error: 500 Internal Server Error
Sorry, the requested URL 'http://localhost:8080/run' caused an error:
Internal Server Error
Exception:
AttributeError("CacheAddress instance has no attribute 'blockNumber'",)
Traceback:
Traceback (most recent call last):
  File "bottle.py", line 862, in _handle
  File "bottle.py", line 1732, in wrapper
  File "hindsight_gui.py", line 161, in do_run
  File "pyhindsight\analysis.py", line 135, in run
  File "pyhindsight\browsers\chrome.py", line 1169, in process
  File "pyhindsight\browsers\chrome.py", line 1019, in get_cache
  File "pyhindsight\browsers\chrome.py", line 1801, in __init__
  File "pyhindsight\browsers\chrome.py", line 1842, in keyToStr
  File "pyhindsight\browsers\chrome.py", line 1642, in data
AttributeError: CacheAddress instance has no attribute 'blockNumber'

I was testing the app using several different Chrome v56 profiles and each profile was extracted in its entirety from a Windows 10 user profile. I am not running the app against a mount point, such as with FTK Imager mount or EnCase PDE. The hindsight log file is attached for your reference.

[hindsight.log.txt](https://github.com/obsidianforensics/hindsight/files/1050583/hindsight.log.txt)

If you need additional information or other tests run, feel free to ping me.

Thanks.

/Chris

**Comment by obsidianforensics** [comment]
Hi Chris,

Thank you for the well-written bug report. I am in the process of finalizing a new release that adds more error checking around cache parsing, so at a minimum the whole app shouldn't crash. 

Would it be possible for you to provide me with the test data that caused the issue? I would like to see which files are causing the issue, as Windows 10 is my normal test system and I haven't seen this before. If not, no problem; you can test the new release against it on your end.

**Comment by cshanahan** [comment]
Ryan,

If you can contact me off-line maybe I can help with the actual data. I cannot share here though. Sorry.

I'd be more than willing to test, whenever you are ready. I have a dozen images of Win10 Pro systems, all with multiple Chrome profiles.

/Chris

**Comment by obsidianforensics** [comment]
Hey Chris,

Sorry for the delay on this. I just put out a new release (https://github.com/obsidianforensics/hindsight/releases) that adds more error handling during cache processing. Can you let me know if this fixes your issue? 

Thanks,
Ryan
