### ISSUE TITLE
Datetime comparison error

### ISSUE THREAD

**Issue by ELAPS0** [obsidianforensics/hindsight#155]
**Describe the problem**
The comparison of two datetime values is incorrect because one of them has null timezone info.

**Screenshots or Console Output**

```
Traceback (most recent call last):
  File "C:\work\hindsight\hindsight.py", line 338, in <module>
    main()
  File "C:\work\hindsight\hindsight.py", line 212, in main
    run_status = analysis_session.run()
  File "C:\work\hindsight\pyhindsight\analysis.py", line 529, in run
    browser_analysis.process()
  File "C:\work\hindsight\pyhindsight\browsers\chrome.py", line 2559, in process
    self.parsed_artifacts.sort()
  File "C:\work\hindsight\pyhindsight\browsers\webbrowser.py", line 137, in __lt__
    return self.timestamp < other.timestamp
TypeError: can't compare offset-naive and offset-aware datetimes

````

**System Details**
 - Analysis System OS (your forensic workstation): Windows 10
 - Method of Running Hindsight: hindsight.py using Python 3.10.11
 - Hindsight version: 20230327.0
 - Target System OS: (the OS you pulled the browser files from): Windows 10
 - Target Browser: Chrome
 - Target Browser Version: 111

**Patch**

```
index e5a54f6..4f473e8 100644
--- a/pyhindsight/browsers/webbrowser.py
+++ b/pyhindsight/browsers/webbrowser.py
@@ -129,6 +129,11 @@ class WebBrowser(object):
             self.interpretation = interpretation

         def __lt__(self, other):
+            if not self.timestamp.tzinfo and other.timestamp.tzinfo:
+                self.timestamp = self.timestamp.replace(tzinfo=other.timestamp.tzinfo)
+            elif self.timestamp.tzinfo and not other.timestamp.tzinfo:
+                over.timestamp = other.timestamp.replace(tzinfo=self.timestamp.tzinfo)
+
             return self.timestamp < other.timestamp

         def __iter__(self):
```

**Comment by obsidianforensics** [comment]
Thanks for reporting this and the patch; sorry it took so long to get merged in!
