### ISSUE TITLE
Type error on xUbuntu 17.10

### ISSUE THREAD

**Issue by kurthbemis** [obsidianforensics/hindsight#17]
```
Bottle v0.12.13 server starting up (using WSGIRefServer())...
Listening on http://localhost:8080/
Hit Ctrl-C to quit.

No handlers could be found for logger "pyhindsight.analysis"
127.0.0.1 - - [14/Jun/2018 16:31:13] "GET / HTTP/1.1" 200 18564
127.0.0.1 - - [14/Jun/2018 16:31:13] "GET /static/styles.css HTTP/1.1" 304 0
127.0.0.1 - - [14/Jun/2018 16:31:13] "GET /static/github.png HTTP/1.1" 304 0
127.0.0.1 - - [14/Jun/2018 16:31:13] "GET /static/slack.png HTTP/1.1" 304 0
127.0.0.1 - - [14/Jun/2018 16:31:13] "GET /static/twitter.png HTTP/1.1" 304 0
127.0.0.1 - - [14/Jun/2018 16:31:13] "GET /static/h.png HTTP/1.1" 304 0
127.0.0.1 - - [14/Jun/2018 16:31:13] "GET /static/fonts/OpenSans-Regular.woff2 HTTP/1.1" 304 0
127.0.0.1 - - [14/Jun/2018 16:31:13] "GET /static/fonts/OpenSans-Light.woff2 HTTP/1.1" 304 0
                     Detected Chrome version:            [     66 ]
                                 URL records:            [   6815 ]
                            Download records:            [    162 ]
                               Cache records:            [  12119 ]
                           GPU Cache records:            [    490 ]
                         Media Cache records:            [    478 ]
                   Application Cache records:            [      0 ]
                              Cookie records:            [   5561 ]
                            Autofill records:            [   6366 ]
                            Bookmark records:            [      3 ]
                       Local Storage records:            [   2240 ]
                                  Extensions:            [     11 ]
                    Extension Cookie records:            [      0 ]
                          Login Data records:            [     51 ]
Traceback (most recent call last):
  File "/home/user/.local/lib/python2.7/site-packages/bottle.py", line 862, in _handle
    return route.call(**args)
  File "/home/user/.local/lib/python2.7/site-packages/bottle.py", line 1740, in wrapper
    rv = callback(*a, **ka)
  File "hindsight_gui.py", line 163, in do_run
    analysis_session.run()
  File "/home/user/src/hindsight/pyhindsight/analysis.py", line 129, in run
    browser_analysis.process()
  File "/home/user/src/hindsight/pyhindsight/browsers/chrome.py", line 1713, in process
    self.get_preferences(self.profile_path, 'Preferences')
  File "/home/user/src/hindsight/pyhindsight/browsers/chrome.py", line 1240, in get_preferences
    pref_item = Chrome.PreferenceItem(url='', timestamp=to_datetime(timestamp[0], self.timezone),
TypeError: 'float' object has no attribute '__getitem__'
127.0.0.1 - - [14/Jun/2018 16:31:44] "POST /run HTTP/1.1" 500 1905

```
Any insight?

**Comment by obsidianforensics** [comment]
I missed this one; sorry about that. Closing this due to time passed and newer Hindsight versions should handle this better.
