### ISSUE TITLE
Crashes after first run, details below

### ISSUE THREAD

**Issue by aidan-gibson** [obsidianforensics/hindsight#194]
**Describe the problem**
Crashes after running

**hindsight.log Snippet**
 
[hindsight.log](https://github.com/user-attachments/files/17686317/hindsight.log)

**System Details**
 - Analysis System OS (your forensic workstation): macOS 14.7
 - Method of Running Hindsight: git cloned Nov 8 2024, installed necessary packages, and `python hindsight_gui.py`
 - Hindsight version: v2024.10
 - Target System OS: (the OS you pulled the browser files from): macOS 14.7
 - Target Browser: Chrome
 - Target Browser Version: 130.0.6723.117 (Official Build) (arm64) 

**Additional context**
```
Traceback (most recent call last):
  File "/Users/aidangibson/.virtualenvs/hindsight/lib/python3.11/site-packages/bottle.py", line 995, in _handle
    out = route.call(**args)
          ^^^^^^^^^^^^^^^^^^
  File "/Users/aidangibson/.virtualenvs/hindsight/lib/python3.11/site-packages/bottle.py", line 2025, in wrapper
    rv = callback(*a, **ka)
         ^^^^^^^^^^^^^^^^^^
  File "/Users/aidangibson/PycharmProjects/hindsight/hindsight_gui.py", line 170, in do_run
    run_status = analysis_session.run()
                 ^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/aidangibson/PycharmProjects/hindsight/pyhindsight/analysis.py", line 527, in run
    browser_analysis.process()
  File "/Users/aidangibson/PycharmProjects/hindsight/pyhindsight/browsers/chrome.py", line 2428, in process
    self.get_cache(c_path, c_dir, row_type='cache')
  File "/Users/aidangibson/PycharmProjects/hindsight/pyhindsight/browsers/chrome.py", line 1871, in get_cache
    for cache_item in cache_items:
  File "/Users/aidangibson/.virtualenvs/hindsight/lib/python3.11/site-packages/ccl_chromium_reader/ccl_chromium_profile_folder.py", line 438, in iterate_cache
    self._lazy_load_cache()
  File "/Users/aidangibson/.virtualenvs/hindsight/lib/python3.11/site-packages/ccl_chromium_reader/ccl_chromium_profile_folder.py", line 159, in _lazy_load_cache
    raise ValueError(f"Data under {cache_path} could not be identified as a known cache type")
ValueError: Data under /Users/aidangibson/Library/Caches/Google/Chrome/Default could not be identified as a known cache type
```

**Comment by aidan-gibson** [comment]
Possibly Related to #133

**Comment by aidan-gibson** [comment]
Note: completes run if I don't include cache

**Comment by obsidianforensics** [comment]
Thanks for the detailed report, I'll take a look. At a minimum it shouldn't crash (that should be quick to fix) - the cache parsing fix may take longer.

**Comment by obsidianforensics** [comment]
Could you try running it again with the cache input set to `/Users/aidangibson/Library/Caches/Google/Chrome/Default/Cache/Cache Data` (instead of `..../Default`)? I tried on a similar system (macOS) and got similar results when not putting the complete cache path, but it parsed after I changed it. 

I'll update the cache input parsing though; Hindsight should be able to find the Cache from the input directory you had put in.

**Comment by obsidianforensics** [comment]
I hit that same JSONL output error recently - I fixed that particular one in the latest release, but created an issue #209 for generally revisiting the JSONL output. 

The Cache parsing got some more safeguards too in the latest release, so hopefully that prevents your crashes. If things still go wrong, can you please re-open this issue or make a new one, whatever fits best? Thanks.
