### ISSUE TITLE
"Could not lock file" error when parsing image mounted with FTK Imager or parsing Volume Shadow Copies

### ISSUE THREAD

**Issue by grayfold3d** [obsidianforensics/hindsight#20]
I'm receiving an error "Could not lock file" in two scenarios:

1. Running FTK Imager v 4.1.1 and attempting to parse the Chrome artifacts on several different images.  
    Images are mounted in FTK as File System/Read Only. 

2. Drive mounted with Arsenal Image Mounter. The same image that failed to parse with FTK works with Arsenal, BUT if I mount the Volume Shadow copies and try to scan one of these, I get the same error.
```
       Start time: 2018-10-03 17:24:51.216
  Input directory: i:\[root]\users\Administrator\AppData\Local\Google\Chrome\User Data\Default
      Output name: c:\cases\Desktop-FTK\Administrator\chrome.xlsx

 Processing:
                     Detected Chrome version:            [     66 ]            
                                 URL records:            [     71 ]            
                            Download records:            [      4 ]            
                               Cache records:            [   1671 ]            
                           GPU Cache records:            [      0 ]            
                         Media Cache records:            [      0 ]            
                              Cookie records:            [    414 ]            
                            Autofill records:            [      7 ]            
hindsight.exe : [6176] Failed to execute script hindsight
At line:1 char:1
+ & "C:\utilities\Hindsight\hindsight.exe" -i  "i:\[root]\users\Adminis ...
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: ([6176] Failed t...cript hindsight:String) [], RemoteException
    + FullyQualifiedErrorId : NativeCommandError
 
Traceback (most recent call last):
  File "hindsight.py", line 293, in <module>
  File "hindsight.py", line 180, in main
  File "pyhindsight\analysis.py", line 129, in run
  File "pyhindsight\browsers\chrome.py", line 1757, in process
  File "pyhindsight\browsers\chrome.py", line 710, in get_local_storage
  File "pyhindsight\browsers\chrome.py", line 1432, in get_prefixed_leveldb_pairs
leveldb.LevelDBError: IO error: i:\[root]\users\Administrator\AppData\Local\Google\Chrome\User Data\Default\Local Storage\leveldb\LOCK: Could not lock file.
```

Same error using the GUI
```
Error: 500 Internal Server Error
Sorry, the requested URL 'http://localhost:8080/run' caused an error:

Internal Server Error
Exception:
LevelDBError('IO error: I:\\[root]\\Users\\mpowers\\AppData\\Local\\Google\\Chrome\\User Data\\Default\\Local Storage\\leveldb\\LOCK: Could not lock file.',)
Traceback:
Traceback (most recent call last):
  File "site-packages\bottle.py", line 862, in _handle
  File "site-packages\bottle.py", line 1732, in wrapper
  File "hindsight_gui.py", line 163, in do_run
  File "pyhindsight\analysis.py", line 129, in run
  File "pyhindsight\browsers\chrome.py", line 1757, in process
  File "pyhindsight\browsers\chrome.py", line 710, in get_local_storage
  File "pyhindsight\browsers\chrome.py", line 1432, in get_prefixed_leveldb_pairs
LevelDBError: IO error: I:\[root]\Users\mpowers\AppData\Local\Google\Chrome\User Data\Default\Local Storage\leveldb\LOCK: Could not lock file.
```

**Comment by obsidianforensics** [comment]
I believe this is caused by mounting the files as read-only. LevelDB uses lock files to ensure only one process is accessing the ldb at a time. I have two theories; either the LOCK file already existed in the evidence and thus Hindsight thinks the ldb is locked and inaccessible, or it is trying to create the LOCK file to lock the ldb for reading, and fails because of the RO mounting. It may have succeeded with Arsenal because I think Arsenal can mount as RO but allow simulated writes.  

I've been wanting to include the capability to create temp copies of files that are locked for SQLite for a while, and it sounds like I should include ldb in this as well. That will be a bigger effort, but for now I'll work on the error handling so this at least won't crash Hindsight. 

Thanks for reporting the issue.

**Comment by grayfold3d** [comment]
OK I think it is the RO mounting. The same image works under Arsenal which I am using the "Write Temporary" option on. I normally mount in FTK using "FIle System/Read Only". If I change to "Block Device / Writable" the error does not occur.

**Comment by EricZimmerman** [comment]
You could try KAPE to extract all the chrome history, then hindsight from there. KAPE normalizes stuff out of volumes and VSCs so this should work
