### ISSUE TITLE
crash

### ISSUE THREAD

**Issue by Tazeg** [obsidianforensics/hindsight#9]
Ubuntu 15.10

./hindsight.py -i '../chromium' -o test

Couldn't import module 'xlsxwriter'; XLSX output disabled.

Couldn't import module 'win32crypt'; cookie decryption on Windows disabled.

Couldn't import module 'pytz'; all timestamps in XLSX output will be in examiner local time (CEST).

 Hindsight v1.6.0
       Start time: 2016-04-08 20:45:17.328
  Input directory: ../chromium
      Output name: test

 Processing:
                     Detected Chrome version:            [  31-49 ]            

 Running plugins:
                 Google Searches (v20150728):      - 0 searches parsed -  
       Generic Timestamp Decoder (v20140816):     - 0 timestamps parsed -  
          Chrome Extension Names (v20150125):   - 0 extension URLs parsed -  
         Time Discrepancy Finder (v20141214):     - 0 differences parsed -  
             Query String Parser (v20150222):    - 0 query strings parsed -  
  Google Analytics Cookie Parser (v20140813):       - 0 cookies parsed -  
         Quantcast Cookie Parser (v20140813):       - 0 cookies parsed -       

 Writing "test.sqlite"
Traceback (most recent call last):
  File "./hindsight.py", line 2139, in <module>
    main()
  File "./hindsight.py", line 2133, in main
    write_sqlite(target_browser)
  File "./hindsight.py", line 2041, in write_sqlite
    for extension in browser.installed_extensions['data']:
TypeError: list indices must be integers, not str

**Comment by Tazeg** [comment]
Notice : i had set the directory "chromium".
With "chromium/Default", it works !
Regards.
