### ISSUE TITLE
Hindsight getting hung on Application Data\Application Data directories

### ISSUE THREAD

**Issue by mgraf444** [obsidianforensics/hindsight#95]
Traceback (most recent call last):
  File "hindsight.py", line 329, in <module>
  File "hindsight.py", line 212, in main
  File "pyhindsight\analysis.py", line 479, in run
  File "pyhindsight\browsers\chrome.py", line 2169, in process
  File "pyhindsight\browsers\chrome.py", line 887, in get_local_storage
FileNotFoundError: [WinError 3] The system cannot find the path specified: 'C:\\Users\\user\\AppData\\Local\\Application Data\\Application Data\\Application Data\\Application Data\\Application Data\\Application Data\\Application Data\\Application Data\\Application Data\\Application Data\\Application Data\\Google\\Chrome\\User Data\\Default\\Local Storage'
[10076] Failed to execute script hindsight

################################################################################

                   _     _           _     _       _     _
                  | |   (_)         | |   (_)     | |   | |
                  | |__  _ _ __   __| |___ _  __ _| |__ | |_
                  | '_ \| | '_ \ / _` / __| |/ _` | '_ \| __|
                  | | | | | | | | (_| \__ \ | (_| | | | | |_
                  |_| |_|_|_| |_|\__,_|___/_|\__, |_| |_|\__|
                                              __/ |
                        by @_RyanBenson      |___/ v2021.04.26

################################################################################

       Start time: 2021-06-10 11:26:44.098
  Input directory: C:\Users
      Output name: Hindsight.xlsx

 Processing:

    Profile: ...Application Data\Application Data\Google\Chrome\User Data\Default
                     Detected Chrome version:            [     83 ]            
                                 URL records:            [     47 ]            
                            Download records:            [      6 ]            
                               Cache records:            [    861 ]            
                           GPU Cache records:            [      0 ]            
                              Cookie records:            [    223 ]            
                            Autofill records:            [      0 ]

Seen this on multiple hosts, specifically Windows 10, command line arguments below.

hindsight.exe -i "C:\Users" -o Hindsight

**Comment by obsidianforensics** [comment]
Interesting, thanks for reporting. I'm betting some weirdness with a shortcut file, I'll take a look.
