### ISSUE TITLE
SyntaxError: invalid syntax and IndexError: list index out of range

### ISSUE THREAD

**Issue by hello-hihi** [obsidianforensics/hindsight#96]
**System Details**
 - Analysis System OS (your forensic workstation): Windows 10]
 - Method of Running Hindsight: hindsight.py using Python 3.7.0 on Windows, hindsight_gui.exe on Windows
 - Hindsight version: 20210426
 - Target System OS: (the OS you pulled the browser files from): Windows10
 - Target Browser: Brave
 - Target Browser Version: Version 1.25.73 Chromium: 91.0.4472.106 (64bit)

**Additional context**

error#1
hindsight.py using Python 3.7.0 on Windows

SyntaxError: invalid syntax

![image](https://user-images.githubusercontent.com/86198644/122681057-7e582800-d22d-11eb-933e-1aac0497388f.png)

error#2
hindsight_gui.exe on Windows

Traceback (most recent call last):
  File "bottle.py", line 868, in _handle
  File "bottle.py", line 1748, in wrapper
  File "hindsight_gui.py", line 170, in do_run
  File "pyhindsight\analysis.py", line 518, in run
  File "pyhindsight\analysis.py", line 426, in generate_display_version
IndexError: list index out of range

![image](https://user-images.githubusercontent.com/86198644/122680996-26212600-d22d-11eb-8bb3-c6203a0f342e.png)

**Comment by obsidianforensics** [comment]
Hi there - thanks for the report. The Brave support in Hindsight has lagged quite a lot, but the good thing (for Hindsight at least) is that Brave has changed to be more like Chrome. If you process the same input path as Chrome, Hindsight should work just fine. I haven't done exhaustive testing on recent Brave versions to see what's different from Chrome, but a quick test run on my own Brave install worked well.
